version: 0.2
phases:
  install:
    runtime-versions:
        java: 8
  build:
    commands:
      - echo Build started on `date`
      - mvn clean 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/aws-build-sample-maven-project-0.0.1-SNAPSHOT.jar
